name: K6 Load Test
on: [push]
jobs:
  build: K6 Load Test
  tuns-on: ubuntu-latest
  steps:
    - name: step 1 - checkout
      uses: actions/checkout@v3

    - name: step 2 - run K6 Load Test
      uses: grafana/k6-action@v0.2.0
      with: 
        filename: scripsts/test.js